### ISSUE TITLE
Decentralise Repository

### ISSUE THREAD

**Issue by devnote-dev** [Botloader/botloader#20]
There are a few parts of the repository that could definitely do with having their own space in the organisation, such as the `botloader-vscode` folder, the `book`, anad `frontend`/`frontend-common`. Having their own repositories means that issues and PRs for a specific section can be more easily organised and tracked.

**Comment by jonastar** [comment]
There's a couple of issues with doing this:

1. What if a issue is relevant to both the frontend and backend?
2. What if you encounter a bug that you don't know is the frontend or backends fault?
3. There's code sharing going on between the frontend and vscode extension (the API client)
4. There's TS code being generated from the rust code (API models) making the backend, frontend and vscode tightly coupled every commit.

It's not worth it at this scale.
